name: flutter_test1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 画面遷移の状態管理に使用
  flutter_bloc: ^8.1.4
  # ハンバーガーメニューの実装に使用
  flutter_bloc_pattern: ^2.3.0
  # ChatGPTなどのリクエストに使用
  http: ^1.2.1
  # 各画面の入力状態の保持に使用
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  # ローカルデータの保存に使用
  hive: ^2.2.3
  path_provider: ^2.1.2
  # 自然な日本語(Noto Sans JPフォント)を使うために必要
  google_fonts: ^6.2.1
  # objectの比較に使用
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:   
    - family: NotoSansJP
      fonts:
        - asset: assets/google_fonts/NotoSansJP-Regular.ttf