name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    # if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # 以下はOptional項目
          # 言語設定
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          # MODEL: gpt-4o # https://platform.openai.com/docs/models
          MODEL: gpt-3.5-turbo # https://platform.openai.com/docs/models
          # PROMPT: # example: Please check if there are any confusions or irregularities in the following code diff:
          top_p: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-top_p
          temperature: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
          max_tokens: 4000
          MAX_PATCH_LENGTH: 4000 # If the Patch/Diff length is greater than MAX_PATCH_LENGTH, it's ignored and not checked. By default, if MAX_PATCH_LENGTH is not set, there is no limit to the patch/diff length...
